### ISSUE TITLE
VCD UI Plugin Seed Incorrect Documentation

### ISSUE THREAD

**Issue by carceneaux** [vmware-samples/vcd-ext-samples#1]
I've worked with the now deprecated [plugin seed](https://github.com/vmware/vcd-ext-sdk/tree/master/ui/vcd-plugin-seed) so I was excited to learn that I didn't have to mess with compiling the API Client anymore. That said following the [documentation for the new plugin seed](https://github.com/vmware-samples/vcd-ext-samples/blob/plugin-seed-9.1/README.md) while setting up a new development environment, I encountered errors.

The issues with the documentation I've highlighted below as found in their specific sections.

**Prerequisites**

The requirements for the development environment setup are lacking. I understand the objective to stay away from providing environment setup instructions for multiple OSes and versions, but more info is needed for a newcomer to get started.

To setup/compile the seed plugin:

* Node 8 is required.
  * Node 12 is the latest version. However, the version of `node-sass` that's specified in the seed plugin `package.json` doesn't support Node 12. I ended up uninstalling Node 12 and installing Node 8 so that `node-sass` would not cause `npm ci` to fail.

To leverage the automated deployment script:

`py manage_plugin.py deploy`

I assume the `py` is for PyPy which I haven't used. Instead of installing PyPy in my environment, I simply used Python with the requirements below and executed as:

`python manage_plugin.py deploy`

* Python 2.x (this really should be Python 3) - [Death Clock](https://pythonclock.org/)
* Python Libraries:
  * requests
  * configparser

**Automated Deploy Method**

This section mentions renaming the `manage_plugin.ini.template` and using the `manage_plugin.py` script. *Neither of these files exist in the repository.*

What I ended up doing was copying the `ui_ext_api.ini.template` and `ui_ext_api.py` files from the [deprecated seed plugin](https://github.com/vmware/vcd-ext-sdk/tree/master/ui/vcd-plugin-seed).

**Comment by jmoroski** [comment]
Thanks for the detailed feedback. Do you happen to know if the current LTS version of node is working (10.x)? Node 8 seems a little dated as a requirement, but LTS support should be reasonable. If not, I can get around to testing it out. I think one of my environments is 10, but I'd have to verify.

**Comment by carceneaux** [comment]
I'll need to check. In some forum where I realized Node / node-sass incompatibility was the issue, it lead me to believe that Node 10 also wasn't supported but I haven't tested it yet.

**Comment by carceneaux** [comment]
I've confirmed that Node 10 works as well. It's just Node 12 then that won't work.

**Comment by jmoroski** [comment]
- updated seed project's package.json for better compatibility with Node 10.x
- added a branch containing a new version of the manage_plugin Python script and updated that branches README with correct usage info and prerequisites
- Referenced Python script with links from seed project README

Note that the new script is not an exact drop in replacement for ui_ext_api.py. It supports registering a plugin, listing plugins, and unregistering a plugin. It does not currently update an existing plugin, but that can easily be added. Register and unregister no longer depend on a folder location and walking through the list of current plugins (making some potentially awkward assumptions). Register takes a plugin directory as an argument, and unregister takes a plugin id as an argument. This _should_ make the script more portable and cut down on duplication.

**Comment by carceneaux** [comment]
@jmoroski I'm loving the new `manage_plugin.py`! Great job!
