### ISSUE TITLE
Seed app routing issue with vCD 10.1

### ISSUE THREAD

**Issue by shubhamkr-cohesity** [vmware-samples/vcd-ext-samples#19]
**Describe the bug**
With vCD 10.1, the angular container version has been upgraded to 8+ in vCD appliance. With this new version, I am encountering routing issue with my existing plugin which worked well otherwise.

Issue:
Not able to navigate using 
`router.navigate(router.navigate([extentionPrefix, 'about'])`

I have setup a router guard in my routing module to redirect certain requests based on user role,
eg
<host>/plugin/ -> Redirect to <host>/plugin/config // Provider view
<host>/plugin/ -> Redirect to <host>/plugin/overview // Tenant view

I handle this redirection through a router guard and call the router (Router) navigate API to redirect the user.

The error I see in v10.1 is, 
`Error: Cannot match any routes. URL Segment: 'about'`

My routes:
`const ROUTES: Routes = [
    {
        path: "", component: SubnavComponent, children: [
            { path: "", redirectTo: "status", pathMatch: "full" },
            { path: "status", component: StatusComponent, canActivate: [RouterGuardService] },
            { path: "about", component: AboutComponent }
        ]
    }
];
`

If I open the URL <host>/plugin/about directly, it works fine.

**To Reproduce**
Steps to reproduce the behaviour:
1. Add a router guard to a route.
2. Redirect the request to a different endpoint through the guard using the navigate() API.

**Expected behavior**
Since the route is valid, the redirect should have worked just fine.

**Screenshots**
![image](https://user-images.githubusercontent.com/48118398/84019992-b2a0d380-a99f-11ea-8c6f-7f3df78f2761.png)

**Desktop (please complete the following information):**
 - OS: Max
 - Browser Chrome

**Comment by nvladimirovi** [comment]
Hello,

Thank you to letting us know about this one. I think 10.1 dev container branch is not ready yet, at this point it's the same like 9.7 - 10.0. (My comment is not relevant if you took the branch implementation from my PR: https://github.com/vmware-samples/vcd-ext-samples/pull/24)

**Comment by nvladimirovi** [comment]
Please refer to our [documentation](https://vmware.github.io/vcd-ext-sdk/)
