### ISSUE TITLE
Plugin Upload

### ISSUE THREAD

**Issue by sweetpeaito** [vmware-samples/vcd-ext-samples#3]
I have an error uploading the plugin with the API . statue:content length is invalid . Also how do i pass the binary parameter .

**Comment by jmoroski** [comment]
> I have an error uploading the plugin with the API . statue:content length is invalid .

Please use the Bug Report issue template to provide an adequate amount of information to aid in identifying and resolving the issue.

>  Also how do i pass the binary parameter

If you're referring to providing the plugin.zip content via curl, this is accomplished using the `--data-binary` argument as seen in the "Upload plugin.zip to vCloud Director" section of the seed plugin's readme:
```bash
# Upload plugin.zip to vCloud Director
# upload path is in the Link response header of the previous call
SERVER="vcloud.example.com" TOKEN="c2f4258224ce4489b4e4474e4e34db15" curl --request PUT --header 'Content-Type: application/zip' --header "x-vcloud-authorization: $TOKEN" --insecure --verbose https://$SERVER/transfer/19d7fafd-6670-4c2a-983f-0b3a49725d2e/plugin.zip --data-binary @dist/plugin.zip
```
