### ISSUE TITLE
Duplicity of plugin names in VCD when upload more than one plugin.zip (seed plugin)

### ISSUE THREAD

**Issue by joaquinniram** [vmware-samples/vcd-ext-samples#34]
Hi, I have tried to figure out how to not duplicate plugin names into VCD UI menu (hamburguer menu).

I could upload and use only one plugin, but when I upload a second one, I see two plugins with the same name into the VCD UI menu (hamburguer menu). How can I work with different seed plugin with uniqueness?

Thanks

**Comment by jmoroski** [comment]
In your i18n.json file try giving the keys unique names. Instead of both being `nav.label`, if one is `plugin1.nav.label` and the other is `plugin2.nav.label` the duplicity should be resolved.

**Comment by joaquinniram** [comment]
Really very thank you for your help, I did it as you said and applied also
into the file "*simple-plugin.module.ts*" and works!!

this.registerExtension(<ExtensionNavRegistration>{
            path: extensionRoute,
            icon: "page",
            nameCode: "plugin2.nav.label",
            descriptionCode: "plugin2.nav.description"
        });

**Comment by nvladimirovi** [comment]
Please refer to our documentation https://vmware.github.io/vcd-ext-sdk/ if you need more info.
