### ISSUE TITLE
upload plugin API : Content Length is Invalid

### ISSUE THREAD

**Issue by sweetpeaito** [vmware-samples/vcd-ext-samples#4]
**Describe the bug**
I run vcd 9.1 in my environment , i am using vcd 9.1 plugin seed vcd-ext-samples-plugin-seed-9.1  link : https://github.com/vmware-samples/vcd-ext-samples/tree/plugin-seed-9.1

upon upload of the plugin , i get content length is invalid error via POSTMAN

**To Reproduce**
1.  create a session for sys admin user : i created a session and obtained the x-vcloud-authorization token
2.register the plugin, providing the same values as in the manifest.json : i provided the values of the  
{
    "urn": "vmware:vcloud:plugin:seed",
    "name": "Simple plugin",
    "containerVersion": "9.1.0",
    "version": "1.0.0",
    "scope": ["service-provider", "tenant"],
    "permissions": [],
    "description": "An example plugin.",
    "vendor": "VMware",
    "license": "Copyright (C) VMware 2017-2018.  All rights reserved.",
    "link": "http://www.vmware.com/support",
    "module": "SimplePluginModule",
    "route": "plugin"
}

3.enable upload on the newly registered plugin (endpoint is in the Location header of 
previous response) : 
--data '{"fileName": "plugin.zip", "size": 56623}'
I passed the same value in the sample 56623 as file size 

4. Upload plugin.zip to vCloud Director : I use the link response of the enable upload API result header as my URL
**Expected behavior**
I expected to receive a 200 ok , upload successful
**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. windows10]
 - Browser [e.g. chrome]

**Additional context**

**Comment by jmoroski** [comment]
> I passed the same value in the sample 56623 as file size

you need to use the actual size of the file (in bytes) that you are uploading. The sample number is just that–a sample.

**Comment by sweetpeaito** [comment]
Good morning ,
Thank you for your response . Do i need to un register the plugin and start the process again ?
kip kool 

    On Tuesday, July 30, 2019, 02:11:34 PM GMT+1, Jeff Moroski <notifications@github.com> wrote:  
 
 

I passed the same value in the sample 56623 as file size


you need to use the actual size of the file (in bytes) that you are uploading. The sample number is just that–a sample.

**Comment by jmoroski** [comment]
> Do i need to un register the plugin and start the process again ?

Yes
The Python scripts give a better experience for managing plugins vs. the pure manual API method if you are interested: https://github.com/vmware-samples/vcd-ext-samples/tree/plugin-manager

**Comment by sweetpeaito** [comment]
I have this already installed , i have ran the script with the list parameter but the unregister returns an error 500.
kip kool 

    On Wednesday, July 31, 2019, 12:39:01 PM GMT+1, Jeff Moroski <notifications@github.com> wrote:  
 
 

Do i need to un register the plugin and start the process again ?


Yes
The Python scripts give a better experience for managing plugins vs. the pure manual API method if you are interested: https://github.com/vmware-samples/vcd-ext-samples/tree/plugin-manager

**Comment by jmoroski** [comment]
what are you specifying to make the unregister call?

**Comment by sweetpeaito** [comment]
Good morning Jeff,
thank you for your response ;
python manage_plugin.py unregister 9ff2ef79-f7db-490d-a297-25daa71d5fa7

i am specifying the plugin id.
Have i passed the parameter properly?
kip kool 

    On Wednesday, July 31, 2019, 04:59:26 PM GMT+1, Jeff Moroski <notifications@github.com> wrote:  
 
 
what are you specifying to make the unregister call?

**Comment by jmoroski** [comment]
The value you specify should be the entire URN returned for the id field in the `list` command, not just the UUID part

**Comment by sweetpeaito** [comment]
AWESOME!!!
Thank you Jeff for your support . It has been a fantastic journey with vcloud ! I woek with a local vcloud service partner in nigeria and my experience as a developer has been fantastic! I am learing new things and hope to learn further . I am very grateful for your support ! My confidence in has just doubled loll. Please if you don mind i would like to be in touch should i need your assistance with respect to plugin develpment or software development on the platform . Thank You!
kip kool 

    On Thursday, August 1, 2019, 09:57:39 AM GMT+1, Jeff Moroski <notifications@github.com> wrote:  
 
 
The value you specify should be the entire URN returned for the id field in the list command, not just the UUID part

**Comment by jmoroski** [comment]
Excellent!

**Comment by sweetpeaito** [comment]
Good day Jeff,
Please i would like to ask a question about vCD. When an SDDC is created , is there a way to assign an end date to how long the SDDC should be valid for ?  I am trying to create an automated process where the SDDC should be disabled when the end date is reached .
Alternatively , I want to build a custom service where the activation and end date can be logged into a custom database and then apply the logic for checking the end date myself . before i do this , i would like to know if vCD has such features or if there is an API to call for this .
Thank You.
kip kool 

    On Thursday, August 1, 2019, 03:01:35 PM GMT+1, Jeff Moroski <notifications@github.com> wrote:  
 
 
Closed #4.
