### ISSUE TITLE
Unknown Path PluginRegistration

### ISSUE THREAD

**Issue by med93121** [vmware-samples/vcd-ext-samples#43]
Hello,
I am trying to add the path relative to my module and I have already verified that the path is successfully taken but unfortunately It is unknown.

![image](https://user-images.githubusercontent.com/83767959/117302757-e61c0480-ae73-11eb-8850-0eb64b01d833.png)
![image](https://user-images.githubusercontent.com/83767959/117302813-f3d18a00-ae73-11eb-8695-79493b0847e2.png)

**Comment by nvladimirovi** [comment]
Please refer to this [docs](https://vmware.github.io/vcd-ext-sdk/)
