### ISSUE TITLE
Plugin with CORS errors

### ISSUE THREAD

**Issue by PhillipOdendaal** [vmware-samples/vcd-ext-samples#44]
Hi guys

Have had much success with plugin development using this repo, but am still experiencing difficulty creating a proxy configuration to enable routing to our system endpoints.

I cant seem to work around the CORS problem by using the Angular HTTPClient.
The VCD Appliance does not recognize the HTTP Headers I provide to the request method.

Is there perhaps any examples / documentation that can provide some detail of creating "proxy routes" for our plugins.

**Comment by aguirrea** [comment]
Hi to everyone! 
I am experimenting also a problem trying to proxy a vCD system from the cloud-director-container sandbox.
I have configured the proxy.json.conf as it:

`{
    "/api/*": {
        "target": "https://vcd-l-01a",
        "secure": true,
        "logLevel": "debug",
        "changeOrigin": true
    },
    "/cloudapi/*": {
        "target": "https://vcd-l-01a",
        "secure": true,
        "logLevel": "debug",
        "changeOrigin": true
    }
}`

and I getting an error when the plugin tries to access the vCD REST API:

`HPM] GET /api/versions -> https://vcd-l-01a
[HPM] GET /api/versions -> https://vcd-l-01a
[HPM] Error occurred while trying to proxy request /api/versions from localhost:4200 to https://vcd-l-01a (DEPTH_ZERO_SELF_SIGNED_CERT) (https://nodejs.org/api/errors.html#errors_common_system_errors)
[HPM] Error occurred while trying to proxy request /api/versions from localhost:4200 to https://vcd-l-01a (DEPTH_ZERO_SELF_SIGNED_CERT) (https://nodejs.org/api/errors.html#errors_common_system_errors)`

I have to generate a certificate?
Thanks

**Comment by nvladimirovi** [comment]
Cloud director containers are no longer supported, please refer to https://vmware.github.io/vcd-ext-sdk/, also if you experience CORS issues you can try to start Chrome (not sure for other browsers) with disabled web security.
