### ISSUE TITLE
After Applying this theme on VCD 10.2.2 there was missing icons as screen shot attached 

### ISSUE THREAD

**Issue by aya-elserrag** [vmware-samples/vcd-ext-samples#69]
**Additional context**
![20210825_145614](https://user-images.githubusercontent.com/56788998/132342879-d032a57d-8fa5-47c8-a0a5-078e68d29e0f.jpg)

**Comment by nvladimirovi** [comment]
Hi,
in your case, using 10.2.2, you have to use clarity 3.1.7.

If this doesn't work, this means that there are custom styles in Cloud Director that are not part of clarity by default respectivly they are not part of the theme generator as well, probably you will have to take and refactor them according to your theme.

Please let us know if this works for you.

**Comment by aya-elserrag** [comment]
still having same issue, please advise .thank you

**Comment by nvladimirovi** [comment]
Using the theme generator to generate either dark or light theme I'm unable to reproduce your issue.
Please delete your node_modules folder, install @clr 3.1.7 (make sure you installed exactly this verison) create and deploy your theme again.

**Comment by nvladimirovi** [comment]
Closing the issue because it's not reproducible using the theme generator and lack of activity. Feel free to reopen the issue if any related problem occur.
