### ISSUE TITLE
Theme Generator VCD 10.2.2 - missing logout options

### ISSUE THREAD

**Issue by crazyflaming** [vmware-samples/vcd-ext-samples#73]
I found the template error. When the browser font is enlarged, the menu options available in the standard view are missing. Please see the attached screenshots.

![w2w2](https://user-images.githubusercontent.com/95022624/143415736-32048c31-07e2-4965-b46f-59204254b9d4.png)
![wswsws](https://user-images.githubusercontent.com/95022624/143415742-8bb2fe94-f1ec-4f19-abf4-de2d2d67a40b.png)
![wswswsw](https://user-images.githubusercontent.com/95022624/143415743-7195c97a-b3fd-4e48-ac0a-9ec7e014e4ea.png)

**Comment by nvladimirovi** [comment]
Hello,
I'm able to reproduce the issue, you can try adding the following to `src/.vcd/common/_common.scss`, and this should fix the issue.

```
.header-actions-right {
    ...
    .sidenav {
        ...
        .nav-list {
            display: block;
        }
    }
} 
```
