### ISSUE TITLE
Unable to generate theme for 10.3

### ISSUE THREAD

**Issue by DSI-BenThomas** [vmware-samples/vcd-ext-samples#82]
**Describe the bug**
Following the steps in the theme-generator branch works fine to generate a theme for 10.1 (Clarity 2.2), however changing the clarity version to ^5.0.1 and attempting to generate the `base` or `dark` theme returns an error.

```
> vcd-theme-generator@1.0.0 build /home/localadmin/theme-generator
> node build-theme "--theme=base" "--optimize"

1
62
Undefined variable: "$clr-default-borderwidth".
182
```

**To Reproduce**
1. Clone repo
2. Update `package.json` to clarity `^5.0.1`
3. Run `npm install` to update package-lock.json
4. Run `npm ci`
5. Run `npm run build -- --theme=base --optimize`

**Expected behavior**
The base theme css file is generated for vCD 10.3

**Additional context**
NodeJS Version is 12.22.12

package.json file

```
{
  "name": "vcd-theme-generator",
  "version": "1.0.0",
  "main": "index.js",
  "license": "BSD-2-Clause",
  "scripts": {
    "build": "node build-theme",
    "gen-dependencies": "node .github/workflows/generate-dependencies.js"
  },
  "devDependencies": {
    "bootstrap": "4.0.0-alpha.5",
    "@clr/icons": "^5.0.1",
    "@clr/ui": "^5.0.1",
    "clean-css-cli": "4.1.11",
    "node-sass": "4.12.0",
    "@webcomponents/custom-elements": "^1.0.0",
    "yargs": "^11.0.0"
  }
}
```

**Comment by kaspars-vilde** [comment]
Same error with nodejs version - v10.19.0

**Comment by nvladimirovi** [comment]
Hi folks,
you can replace the usage of `clr-default-borderwidth `
with `clr-table-borderwidth` in `src/.vcd/vcd.scss`.

And it has to be just fine.

**Comment by nvladimirovi** [comment]
Fixed.
