### ISSUE TITLE
Overlapping of Navigation Menu items of Two different seed plugins.

### ISSUE THREAD

**Issue by cs-chandu** [vmware-samples/vcd-ext-samples#88]
**Describe the bug**
We recently developed and deployed a UI plugin for the vCD provider UI.  This plugin enables information rendering in an iframe when accessed through the "More > Documentation" option. However, we have encountered an issue when attempting to deploy another plugin that offers redirections when we click that More > FooBar item. When both plugins are published simultaneously, the menu item name and functionality of the first-deployed plugin become overlapped.

We are currently investigating whether this is a bug, and exploring options for combining the functionality of both plugins into a single, cohesive plugin.

**Comment by cs-chandu** [comment]
@tsimchev I would appreciate your thoughts and suggestions in here. :)

**Comment by nvladimirovi** [comment]
Hey @cs-chandu check your localisation files of both plug-ins, the localisation files are in JSON format and the keys must be unique for every UI Plug-in.

**Comment by nvladimirovi** [comment]
The localization JSON files are in `./src/public` there prefix all JSON keys with something unique,
also the route of every plugin again has to be unique (in `manifest.json`).

**Comment by nvladimirovi** [comment]
@cs-chandu by the way you can check the documentation here for more info and features.
https://github.com/vmware/vcd-ext-sdk -> https://vmware.github.io/vcd-ext-sdk/
