### ISSUE TITLE
building plugin for vcd 10.5

### ISSUE THREAD

**Issue by swathishetty** [vmware-samples/vcd-ext-samples#90]
_We are currently looking to create different samples that use newer Angular/Clarity versions, at the expense of vCD backward compatibility, for plugin authors who want to leverage newer libraries, or don't have as large of an interop matrix to support._

_Originally posted by @jmoroski in https://github.com/vmware-samples/vcd-ext-samples/issues/9#issuecomment-534236920_

@jmoroski I came across this in - https://github.com/vmware-samples/vcd-ext-samples/issues/9. Can we now build the VCD plugin UI with the higher angular version? (14.X) . Trying to build a vcd plugin on - 10.2.X.  #Thanks

**Comment by nvladimirovi** [comment]
Hello @swathishetty,
you can check this article https://blogs.vmware.com/cloudprovider/2023/04/developing-extensions-for-vmware-cloud-director-service.html and the related links inside. It explains the new way of developing Extensions for VMware Cloud Director.

We currently support Angular 15 for Cloud Director 10.5 (Castor) and Angular 9 for older releases.
We are in the process of documenting how Angular 15 works.

However,
if you want to see an example of how to develop Angular 15 UI Plugin please see my PR here https://github.com/vmware/cloud-director-extension-standard-library/pull/21
Don't hesitate to ask questions directly in https://github.com/vmware/cloud-director-extension-standard-library/issues until we finish our [Documentation](https://developer.vmware.com/docs/18054).

Cloud Director Extension Standard Library will become our central repository and you can please your questions and feature requests there.

**Comment by swathishetty** [comment]
> nvladimirovi

Thank you for PR and the details.  I tried running the emulator and I am getting the below error.

npm
run start

> emulator@1.0.0 start
> node ./node_modules/@vcd/ui-emulator/utils/lib/emulator-start.js ./config.json

Setting auth token
Updating proxy config
Updating Plugins
Updating angular.json
Updating tsconfig.emulator.json
node:events:368
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (node:internal/child_process:288:12)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn npm',
  path: 'npm',
  spawnargs: [ 'run', 'build' ]
}
Any suggestions on this would be helpful.

**Comment by nvladimirovi** [comment]
Do you follow the project structure of emulat or ui-plugin folder next to each other, and use Node 14.20.

**Comment by swathishetty** [comment]
@nvladimirovi I tried cloning the same repo mentioned in your PR. I am using node 16.13.0
![image](https://github.com/vmware-samples/vcd-ext-samples/assets/1817776/ba82fdf5-c101-4365-a2c7-15af94429485)

**Comment by nvladimirovi** [comment]
Got it, okay please try to use NodeJS 14.20.

**Comment by swathishetty** [comment]
@nvladimirovi I am trying to import an external UI module. The build is success, after i import the plugin to vcd 10.5, i see the below errors. If I remove the module, the plugin loads properly. Is it something to do with the plugin builder? if this needs any additional configuration please let me know.
![image](https://github.com/vmware-samples/vcd-ext-samples/assets/1817776/15474f2b-da8c-4b2d-a373-953e6396c6f7)
